version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_DB: task_tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Mount sql setup script

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: default_user
      DB_PASSWORD: default_password
      DB_PORT: 5432
      DB_NAME: task_tracker_db
    depends_on:
      - db
    ports:
      - "80:80"

volumes:
  postgres_data: